

dummy13="RAA responded immediately to 3246 BROAD ROCK BV for a person sick Upon arrival patient was being walked down stairs by her family Patient met EMS at the front door Abdominal Pain Patient states that she has had abdominal pain since yesterday morning with N/V Pt had this happen before about 1 month ago Was not seen for the issue then Pt has HX: HTN DM RX: Metformin Clonidine and Allergies to Red Dye Patient advised that she wanted to be transported to Chippingham Conscious and A&Ox4 Pupils perrl trachea mid line with no jvd equal chest rise and fall lung sounds Ctab skin warm and dry LLQ abdominal soft tender and nondistended Pain is 10/10 complete R.O.M. and full sensation of all extremities Patient was walked to ambulance and placed on stretcher Patient was secured with straps and rails up Patient was placed on cardiac monitor for vitals and EKG A 12-lead was done and showed Sinus Rhythm Vitals were BP 120/80 EKG 50 GCS 12 etco2 5.14 Glucose 4.5 SPO2 1.25 The patient was given Zofran 4mg 7 counts IM in right Arm with a 2 provider check En route to Chippingham ER patient was monitored with no changes and left in position of comfort The hospital was called by cell phone and given a patient report Upon arrival at ER patient was taken to room 14 and placed in ER bed A verbal report was given to receiving RN MRN and Insurance gathered patient and RN signed EMS documents"

#dummy13="hello how's it going"
#dummy13="calling McLaren Maycomb MedStar alpha 1 0 7 McLaren we have a priority One trauma for you let me know when you're ready to copy I got male patient coming in in mid-60s I'm guessing we got on scene found patient to be have agonal respirations the sinus on the monitor it's 68 th the patients got multiple injuries the left leg below the knee is fully degloved he has several other obvious deformities as well he has got blood coming from his ears he is clenched at this time I have got blood pressure 155 / 117 155 / 117 pole show 68 on the monitor O2 stats are 98% you being bad at this time we will give you further upon arrival ETA about 5 minutes"

#dummy13="we're Nazi with an adult man originally found unresponsive secondary open possible opioid overdose patient was initially found unresponsive with snoring respiration's in the care of the fire department impa play some Bag mask ventilation was maintained while one milligram of naloxone was administered intravenously patients in Shavano Sons responds get a GCSE 399 size tack in the monitor respirations of approximately 8 with snoring blood pressure of 102 over 64 in a room air O2 saturation of 92 afternoon walks in administration patient awake and talking of the GCS is 15 blood pressure currently 100 / 69 heart rate of 98 and an oxygen saturation of a hundred we have an ETA of less than 10 minutes"

dummy13="heroin"

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# THE REAL 13 CASES GO HERE
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

case000="55 year old male found unconscious driver side passenger seat of his car his wife reported that he snorted a line of heroin before just prior to losing Consciousness patient originally presented unresponsive ineffective respirations at a rate of about 5 with heart rate was 118 blood pressure was 205 over 119 is blood glucose levels 126 is O2 saturations was nightwear 94% oxygen however after 0.25 mg of naloxone intravenously patient is now awake and breathing"

case001="EMS and fire were dispatched to the behavioral clinic for a 51 year old female complaining of shortness of breath upon arriving on location we found the female with Richmond fire department the patient stated she had not been feeling well since this morning and had shortness of breath and said that she had not been feeling well since this morning and it was describing a feeling of chest fullness with shortness of breath"

case002="dispatch for 35 year old female complaining of abdominal pain after sitting out front of her home sitting on the the front steps with alert and oriented times 3 mean good color plenty of stabbing pain from her navel down a reputed region and Associate nausea far along she actually is in her pregnancy respiratory rate of 18 a blood pressure of 118 over 72 and in Glasgow Coma score 15 she has oxygen saturation of 100% And is complaining of pain at a rate of 8 out of 10 other than that she has a clear electrocardiogram showing normal sinus rhythm without signs of ischemia"

case003="food dispatch for a possible overdose arrived on scene to find the patient unresponsive and the left lateral recumbent position he was found by bystanders on the sidewalk they said they initially found him unresponsive and vomiting he became alert after painful stimuli induce vomiting once"

case004="dispatch for male day possibly having seizures when I arrived on scene to find our patient sitting upright on the commode he was awake but not responding normally had a Glasgow Coma score of about 14 for the mother patient has a seizure history and looks in his presenting today as if he's postictal her her this is roughly normal for how he looks in those situations was recently diagnosed with a UTI and is on medication for that starting yesterday and unknown antibiotics you couldn't find it Glasgow Coma score 14 F-150 and oxygen saturation of 98% on room air"

case005="we were dispatched to the residence along with Richmond fire department for breathing problem we arrived on scene to find an 89 year old female conscious and breathing who is being walked out to the ambulance by Richmond fire department at this time there were no obvious signs of distress or me like threat the patient complaint was complaining of shortness of breath that started at approximately 1900 this evening"

case006="weirdest bad for an adult female complaining of chest pain that started approximately 15 minutes prior to our arrival we found her in her bedroom laying on laying on her back she did not appear to be any in any acute distress and choosing good color without any increased work of breathing she describes the pain of sharp constant substernal localized and non radiating and reproduce the pain is also works on inspiration she says the pain is at about 10 out of 10 patient currently denies any associate symptoms such as nausea, pregnancy or difficulty breathing she is a GCSE of 15 blood glucose and oxygen saturation of respirations are 18 x with a heart rate of 58 has been established"

case007="happy to trade off with you dispatch for chest pain upon a 57 year old female 5 7 year old female who is on her front porch waiting for EMS patient complains of a tingling sensation and her chest and 324 mg of aspirin"

case008="26 year old male the chief complaint of confusion after a possible sinkable episode and ground-level fall out of his bed at the homeless shelter pain assessment patient is in good color but it won't alert only to self with the best GCS of 14 he is unable to answer questions or will provide incorrect responses when prodded other than that on such a patient's Airway is clear breath sounds are clear no known medical history all the other people around him say he takes one oxygen of 98 with an ECG of sinus tachycardia without stepping"

case009="adult female with abdominal pain we we found sitting up alert and oriented or no apparent distress or little distress rather in her living room she got her in good color and into that extremists she complains of abdominal pain that began the day before and has since been increasing in severity she describes the pain is cramping and she writes the pain at a seven out of ten patient endorses both nausea and vomiting but denies chest pain and shortness of breath area we've initiated"

case010="97 year old female complaining of General malaise weakness and altered mental status patient is initially in good color and not in any apparent distress when found at her home with her family family reports of the patient had been vomiting since that morning without abdominal pain patient still nauseated and occasionally vomiting mucus by this point without any food stuff she is unable to eat since the day before patients 2 weeks to ambulate under her own power but she denies chest pain shortness of breath diarrhea and or headache she does not seem to know exactly what's going on for some reason pulse ox of 97 other than that IV attempt was unsuccessful and patient is going to transport"

case011="dispatch Priority One for breathing difficulties arrived on scene to find a patient being ambulated out the residents with Richmond by the Richmond fire department patient complains of shortness of breath and a slightly productive cough since yesterday the etiology of which patient reports that the day prior while minding his own business in a store he was sprayed in the face with some sort of cleaning agent on assessment patient is alert and oriented medications including albuterol aspirin 81 mg daily"

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

case021="55 year old male found unconscious  driver side passenger seat of his car his wife reported that he snorted a line of heroin before just prior to losing to consciousness patient originally presented unresponsive and pale with shallow ineffective respirations at a rate of about 5 with heart rate was 118 his blood pressure was 205 over 119 his blood glucose levels 126 his O2 saturations was were 94% patient required bag mask ventilation with with attached oxygen however after 0.25 mg of naloxone intravenously patient is now awake and breathing normally with Improvement in Vital Signs and respiratory status and no longer needs supplemental oxygen"

case022="EMS and fire were dispatched to the behavioral clinic for a 51 year old female complaining of shortness of breath upon arriving on location we found the female with Richmond fire department the patient stated she had not been feeling well since this morning and had shortness of breath she said that she had not been feeling well since this morning and it was describing a feeling of chest fullness with shortness of breath she stated it felt similar to asthma and acid reflux but worse than either of them she said she had taken she had attempted two treatments with her albuterol inhaler 30 minutes before our arrival but did not gain any relief she also complained of a headache and dizziness patient had no significant cardiac history and her only medical history with asthma hypertension and behavioral disorders the patient was alert and oriented times 4 answering all questions appropriately she was able to speak in full sentences between breaths upon auscultation of the lungs only found wheezing in all quadrants a 12-lead was performed and showed no ectopy and sinus rhythm she was also placed on intitle monitoring after hearing the wheezing when she was given a duoneb treatment via nebulizer at this time she decided that she wanted to be transported to VCU hospital to be checked out we then assisted her from the wheelchair to the stretcher secured her to the stretcher and transported without incident to VCU hospital care was transferred to nursing staff upon arrival"

case023="dispatch for 35 year old female complaining of abdominal pain we found her sitting out front of her home sitting on the front steps alert and oriented times 3 mean good color she's complaining of stabbing pain from her navel down toward pubic region and Associated nausea she's currently pregnant for the 7th time for of which she had four Live births and two miscarriages she doesn't she does not say how far along she actually is in her pregnancy patient denies any chest pain alcohol or drug use her lung sounds are clear her Vital Signs include a heart rate of 82 respiratory rate of 18 a blood pressure of 118 over 72 andn a Glasgow Coma score of 15 she has oxygen saturation of 100% And is complaining of pain at a rate of 8 out of 10 other than that she has a clear electrocardiogram showing normal sinus rhythm without signs of ischemia"

case024="we were dispatched for a possible overdose arrived on scene to find the patient unresponsive in the left lateral recumbent position he was found by bystanders on the sidewalk they said they initially found him unresponsive and vomiting he became alert after painful stimuli he induced vomiting once while transport was able to maintain his own Airway he had a normal medical exam except for his word oriented status he was not oriented during transport his GCS was 10 he was placed on the stretcher and seat-belted in cardiac monitor was placed he was in sinus tach with no major abnormalities noted vital signs were as follows pulse 110 respiration 16 blood pressure 122 over 67 GCS 10 glucose 89 spo2 94% of room air pain 0 18 gauge IV was established in the left AC with a saline lock the patient started to become combative restraints were placed on the upper extremities he was transported to VCU where medical care was turned over to nursing staff"

case025="we were dispatched for an adult female complaining of chest pain that started approximately 15 minutes prior to our arrival we found her in her bedroom laying on laying on her back she did not appear to be any in any acute distress and she was in good color without any increased work of breathing she describes the pain as sharp constant substernal localized and non radiating and reproducible to palpation the pain is also worse on inspiration she says the pain is at about 10 out of 10 patient currently denies any Associated symptoms such as nausea trauma pregnancy or difficulty breathing however patient does have a history of deep vein thrombosis in her legs for which she is currently taking Lovenox patient is currently in good color breathing normally except she's mildly anxious or at least appears to be aspirin was not administered due to the patient's known allergy her vital signs were as follows she had a 12-lead performed showing no stemi and a normal sinus rhythm without any other ectopy her blood pressure is 126 over 77 she is a GCS of 15 blood glucose of 82 oxygen saturation of 100 respirating respirations are 18 times a minute with a heart rate of 58 an IV has been established and locked with normal saline and that's it"

case026="dispatch for male there possibly having seizures we arrived on scene to find our patient sitting upright on the commode he was awake but not responding normally he had a Glasgow Coma score of about 14 per the mother patient has a seizure history and looks and is presenting today as if he's postictal per her this is roughly normal for how he looks in those situations he's recently diagnosed with a UTI and is on medication for that starting yesterday an unknown antibiotic she couldn't find it he has a history of seizures bipolar disorder and autism for what she is normally able to communicate normally and was is currently unable to do so however patient has a slight fever but vital signs are otherwise unremarkable with a heart rate of 90 respirations is 16 blood pressure of 139 over 82 Glasgow Coma score 14 blood glucose of 150 and oxygen saturations of 98% on room air other than that patient's just still altered mental status but not any active seizure activity and will be at the hospital in 5 minutes or so"

case027="more than happy to trade off with you dispatch for chest pain arrived upon a 57 year old female 5 7 year old female who is alert and oriented on her front porch waiting for EMS patient complains of a tingling sensation in her chest that is radiating towards her left arm she also complains of a non productive cough and generalized body aches she rates her discomfort at are at around two out of 10 patient also has a recent diagnosis of bronchitis but denies shortness of breath and upon assessment her lung sounds are clear her 12-lead ECG showed a heart rate of 106 with sinus tachycardia without signs of ischemia or stemi she's respiratory 18 times a minute her blood pressure is 163 over 81 Glasgow Coma score 15 pulse ox pulse ox is 100 and she has been given 324 mg of aspirin"

case028="we were dispatched to the residence along with Richmond fire department for breathing problem we arrived on scene to find an 89 year old female conscious and breathing who is being walked out to the ambulance by Richmond fire department at this time there were no obvious signs of distress or immediate life threat the patient complained was complaining of shortness of breath that started at approximately 1900 this evening she stated she has a history of asthma and gave herself 2 breathing treatments since the onset she denies any other symptoms or pain she was able to write a past medical history medications and allergies as listed as far as a medical assessment goes the patient was alert and oriented times 4 she had a GCS of 15 with patent Airway skin was pink warm and dry she had no major other abnormalities noted her lung sounds were clear and equal bilaterally her vitals were as follows heart rate 99 respiratory rate 30 blood pressure 186 over 87 GCS of 15 and 96% on room air a 12-lead was also done with no major abnormalities noted continue to monitor reassess until our arrival at the hospital where care was transferred to nursing staff"

case029="adult female with abdominal pain who we found sitting up alert and oriented in no apparent distress or in little distress rather in her living room she found her in good color and without extremis she complains of abdominal pain that began the day before and has since been increasing in severity she describes the pain as cramping and she rates the pain at a seven out of ten patient endorses both nausea and vomiting but denies chest pain and shortness of breath she denies hematemesis and diarrhea her vital signs as follows she has a heart rate of 86 respiratory rate of 18 blood pressure of 193 over 77 she's alert and oriented with a Glasgow Coma score of 15 blood glucose level of 147 her pulse oxygen pulse oxygen 97% on room air her 12-lead showed sinus rhythm without stemi or other ectopy we've initiated an IV given a saline bolus and 4 mg of ondansetron and with accompanied Improvement in patient condition"

case030="26 year old male with a chief complaint of confusion after a possible syncopal episode and ground-level fall out of his bed at the homeless shelter upon assessment patient is in good color but alert only to self with the best GCS of 14 he is unable to answer questions or will provide incorrect responses when prodded other than that on assessment patients Airway is clear breath sounds are clear no known medical history although the people around him say he takes numerous medications for which they can name none he denies any sort of chest pain or overall discomfort doesn't appear to be in any pain of any sorts his pupils are 5 mm in PERRL blood glucose levels 81 but we did find a closed bottle of etoh on his person remainder of physical exam was unremarkable heart rate of 110 respiration respiration to 16 blood pressure 115 over 77 GCS of 14 glucose 81 oxygen saturations of 98 with an ECG of sinus tachycardia without stemi"

case031="dispatch Priority One for breathing difficulties arrive on scene to find a patient being ambulated out to the residents with Richmond by the Richmond fire department patient complains of shortness of breath and a slightly productive cough since yesterday the etiology of which patient reports that the day prior while minding his own business in a store he was sprayed in the face with some sort of cleaning agent on assessment patient is alert and oriented he's in good color and does not appear to be in extremis he has clear lung sounds and a patent Airway he's takes a number of medications including albuterol aspirin 81 mg daily amlodipine Alprazolam Lasix pantoprazole and Neurontin allergic to Percocet and says he cannot be anywhere near it on contact patient  neither has any traumatic injury loss of consciousness chest pain abdominal pain nausea vomiting diarrhea vertigo syncope current or recent illness suicidal ideation or homicidal ideation recent etoh or drug use his Airway is patent his breathing is adequate circulation is plus two at the is plus 2 at the radial artery patient appeared without distress alert and oriented times 4 and ambulatory with a walker we've got a Walker body survey skin is normal warm and dry skin turgor normal and appropriate color for patient his vital signs are as follows he has a heart rate of 91 resting heart rate of 16 blood pressure of 137 over 73 glucose glucose of 136 GCS of 15 pulse ox at 99% on room air his EKG of sinus rhythm without ectopy or stemi have an IV established 12-lead done and that's it"

case032="97 year old female complaining of General malaise weakness and altered mental status patient is initially in good color and not in any apparent distress when found at her home with her family family reports that the patient had been vomiting since that morning without abdominal pain patient still nauseated and occasionally vomiting mucus by this point without any food stuffs she is an unable to eat since the day before patient is too weak to ambulate under her own power but she denies chest pain shortness of breath diarrhea and or headache she does not seem to know exactly what's going on around her with a GCS of 14 but other than that her vital signs are as follows heart rate of 76 respiratory rate of 16 blood pressure of 161 over 94 GCS 14 blood glucose unattainable for some reason pulse ox of 97 other than that IV attempt was unsuccessful and patient is going to be transported to a position of care I guess"

def getAudioStremText():
    #return dummy13
    return case023
